# Generated by Django 4.2.1 on 2023-10-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0002_regmodel_alter_add_promodel_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="cartmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proid", models.IntegerField()),
                ("file", models.FileField(upload_to="webapp/static")),
                ("name", models.CharField(max_length=30)),
                ("des", models.CharField(max_length=60)),
                ("pri", models.IntegerField()),
                ("offer", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="wishmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proid", models.IntegerField()),
                ("file", models.FileField(upload_to="web_app/static")),
                ("name", models.CharField(max_length=30)),
                ("des", models.CharField(max_length=60)),
                ("pri", models.IntegerField()),
                ("offer", models.CharField(max_length=30)),
            ],
        ),
    ]
