# Generated by Django 4.2.1 on 2023-10-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0003_cartmodel_wishmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="add_promodel", old_name="name", new_name="pname",
        ),
        migrations.RenameField(
            model_name="cartmodel", old_name="name", new_name="pname",
        ),
        migrations.RenameField(
            model_name="wishmodel", old_name="name", new_name="pname",
        ),
        migrations.AlterField(
            model_name="cartmodel",
            name="file",
            field=models.FileField(upload_to="web_app/static"),
        ),
    ]
