# Generated by Django 4.2.1 on 2023-10-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0004_rename_name_add_promodel_pname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=50)),
                ("pincode", models.IntegerField()),
                ("phone", models.IntegerField()),
                ("pri", models.IntegerField()),
                ("pname", models.CharField(max_length=30)),
                ("payment", models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
