# Generated by Django 4.2.1 on 2023-10-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0006_cartmodel_user_checkout_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="cartmodel", name="user",),
        migrations.RemoveField(model_name="checkout", name="user",),
    ]
