# Generated by Django 4.2.1 on 2023-10-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0007_remove_cartmodel_user_remove_checkout_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="proid",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
