# Generated by Django 4.2.1 on 2023-10-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0008_checkout_proid"),
    ]

    operations = [
        migrations.RemoveField(model_name="checkout", name="proid",),
    ]
