# Generated by Django 4.2.1 on 2023-10-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0010_remove_cartmodel_offer_remove_wishmodel_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartmodel",
            name="offer",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wishmodel",
            name="offer",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
