# Generated by Django 4.2.1 on 2023-10-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0011_cartmodel_offer_wishmodel_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="file",
            field=models.FileField(default=1, upload_to="web_app/static"),
            preserve_default=False,
        ),
    ]
