# Generated by Django 4.2.1 on 2023-11-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0012_checkout_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="cardmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cno", models.IntegerField()),
                ("mm", models.IntegerField()),
                ("yy", models.IntegerField()),
                ("cvv", models.IntegerField()),
                ("cname", models.CharField(max_length=30)),
            ],
        ),
    ]
